name: frontend
description: "Social Circle"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  connectivity_plus: ^6.1.4
  equatable: ^2.0.7
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  hive_ce_flutter: ^2.3.1
  http: ^1.4.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  freezed: ^3.0.6
  hive_ce_generator: ^1.9.1
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true

  assets:
    - lib/core/asset/chat.png
  fonts:
    - family: Poppins
      fonts:
        - asset: lib/core/font/Poppins-SemiBold.ttf
          weight: 600
    - family: Inter
      fonts:
        - asset: lib/core/font/Inter-Regular.ttf
          weight: 400
